(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/xia-editor/xia-editor"],{1769:function(t,e,n){},4216:function(t,e,n){"use strict";var i=n("1769"),o=n.n(i);o.a},"51c4":function(t,e,n){"use strict";n.r(e);var i=n("7409"),o=n("8817");for(var r in o)["default"].indexOf(r)<0&&function(t){n.d(e,t,(function(){return o[t]}))}(r);n("4216");var c=n("828b"),a=Object(c["a"])(o["default"],i["b"],i["c"],!1,null,null,null,!1,i["a"],void 0);e["default"]=a.exports},7409:function(t,e,n){"use strict";n.d(e,"b",(function(){return i})),n.d(e,"c",(function(){return o})),n.d(e,"a",(function(){}));var i=function(){var t=this.$createElement;this._self._c},o=[]},8817:function(t,e,n){"use strict";n.r(e);var i=n("9019"),o=n.n(i);for(var r in i)["default"].indexOf(r)<0&&function(t){n.d(e,t,(function(){return i[t]}))}(r);e["default"]=o.a},9019:function(t,e,n){"use strict";(function(t){Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var n={props:{value:{type:String,default:""},placeholder:{type:String,default:"开始输入..."}},data:function(){return{readOnly:!1,formats:{}}},methods:{shibieText:function(t){var e=this;this.createSelectorQuery().select("#editor").context((function(n){e.editorCtx=n.context,e.editorCtx.setContents({html:t})})).exec()},editText:function(t){this.$emit("editorChange",t.detail.html)},readOnlyChange:function(){this.readOnly=!this.readOnly},onEditorReady:function(){var t=this;this.createSelectorQuery().select("#editor").context((function(e){t.editorCtx=e.context,setTimeout((function(){t.editorCtx.setContents({html:t.value})}),1e3)})).exec()},undo:function(){this.editorCtx.undo()},redo:function(){this.editorCtx.redo()},format:function(t){var e=t.target.dataset,n=e.name,i=e.value;n&&this.editorCtx.format(n,i)},onStatusChange:function(t){var e=t.detail;this.formats=e},insertDivider:function(){this.editorCtx.insertDivider({success:function(){console.log("insert divider success")}})},clear:function(){this.editorCtx.clear({success:function(t){console.log("clear success")}})},removeFormat:function(){this.editorCtx.removeFormat()},insertDate:function(){var t=new Date,e="".concat(t.getFullYear(),"/").concat(t.getMonth()+1,"/").concat(t.getDate());this.editorCtx.insertText({text:e})},insertImage:function(){var t=this;t.$api.upload((function(e){t.editorCtx.insertImage({src:t.$base.url+"upload/"+e.file,alt:"图像",success:function(){console.log("insert image success")}})}))}},onLoad:function(){t.loadFontFace({family:"Pacifico",source:'url("./Pacifico.ttf")'})}};e.default=n}).call(this,n("df3c")["default"])}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/xia-editor/xia-editor-create-component',
    {
        'components/xia-editor/xia-editor-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('df3c')['createComponent'](__webpack_require__("51c4"))
        })
    },
    [['components/xia-editor/xia-editor-create-component']]
]);
